export type { BorderType } from './border'
export { border } from './border'
export type { BreakpointsType } from './breakpoints'
export { breakpoints } from './breakpoints'
export type { FontType } from './fonts'
export { font } from './fonts'
export { mediaQuery } from './mediaQuery'
export type { SizeType } from './size'
export { size } from './size'
export type { SpacingType } from './spacing'
export { spacing } from './spacing'
