name: CI
"on":
  push:
    branches:
      - main
  pull_request: null
concurrency:
  group: "ci-${{ github.ref_name }}"
  cancel-in-progress: true
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: |
          git fetch --no-tags --prune --depth=5 origin main

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm cache dir)"

      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install modules
        run: pnpm

      - name: Run lintings
        run: pnpm lint
  Typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: 'echo "::set-output name=dir::$(pnpm cache dir)"'
      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: "${{ steps.pnpm-cache-dir-path.outputs.dir }}"
          key: "${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}"
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install modules
        run: pnpm
      - name: Run typechecks
        run: pnpm typecheck
